### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by RobLoach** [ajgarlag/AjglComposerSymlinker#1]
Update to the latest Composer API?

**Comment by ajgarlag** [comment]
Please, can you elaborate your issue?

**Comment by RobLoach** [comment]
Mind adding some documentation? Not quite sure how to use this :+1:

**Comment by ajgarlag** [comment]
Sure... I'm giving some love to this old package. I'll release a new version with an improved README this week.

**Comment by ajgarlag** [comment]
@RobLoach I've improved the code and updated the README. Please, review it if you can. I'm planning to tag the new release in a couple of days.

**Comment by ajgarlag** [comment]
New version has just been released

**Comment by RobLoach** [comment]
Thanks a lot, @ajgarlag! I'll check this out on a project :+1:
