### ISSUE TITLE
Link to files failed on Windows

### ISSUE THREAD

**Issue by darkelfe14728** [ajgarlag/AjglComposerSymlinker#9]
As linking on Windows uses NTFS Junction, linking files failed.
I'm not sure if there is a workaround for that. If not, then I suggest adding a warning in the README about that.

**Comment by ajgarlag** [comment]
> As linking on Windows uses NTFS Junction, linking files failed.

Sorry, but I do not understand your comment here. What's the cause of the fail: a misuse of the junction function in the code, or a file system that doesn't support it (like FAT32, UDF or exFAT)?

Would you like to work on a PR to copy files when the link fails? I don't need this feature, but I'm open to contributions.

**Comment by darkelfe14728** [comment]
That's a system limitation: NTFS junction can only be used with directories and volumes, not files.

Like I said, I don't know if there is some workarounds except symbolic links, but it require administrator privileges to work, so not very useful with composer.
At this time, I suggest explicitly said in README that files links doesn't work on Windows, only directories links.

**Comment by ajgarlag** [comment]
Thanks for you comment, I don't use Windows and didn't know about that limitation.

Now I understand the issue. So a workaround would be to copy the source if the junction fails. Please, open a PR if you need this feature.

**Comment by darkelfe14728** [comment]
Not really no. I have use directory link instead and works perfectly.

**Comment by ajgarlag** [comment]
I'll keep this open until README update.
Thanks @darkelfe14728.
